# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Usuario\Desktop\PROYECTOS\AppRes V 1.0\ui_archivos\ingreso_pasajeros.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 800))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QFrame{\n"
"background-color: rgb(255, 230, 212)\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_registro = QtWidgets.QFrame(self.centralwidget)
        self.frame_registro.setStyleSheet("QGroupBox{\n"
"    background-color: rgb(204, 204, 204);\n"
"    border-width: 2px;\n"
"    border-style: solid;\n"
"    border-color: rgb(131, 131, 131);\n"
"    border-radius: 5 px;\n"
"    margin-top: 4ex;\n"
"    margin-left: 2ex;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left; /* position at the top left */\n"
"    padding: 0 3px;\n"
"}\n"
"\n"
"QTableView{\n"
"    background-color: rgb(225, 225, 225);\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(131, 131, 131);\n"
"    border-radius: 3 px;\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"    background-color: rgb(204, 204, 204);\n"
"    border: 1px solid rgb(131, 131, 131);\n"
"    border-style: solid;    \n"
"    font-size: bold 12px;\n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section{\n"
"    background-color: rgb(204, 204, 204);\n"
"    border: 1px solid rgb(131, 131, 131);\n"
"}")
        self.frame_registro.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_registro.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_registro.setObjectName("frame_registro")
        self.groupBox_pasajero = QtWidgets.QGroupBox(self.frame_registro)
        self.groupBox_pasajero.setGeometry(QtCore.QRect(120, 70, 920, 310))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_pasajero.setFont(font)
        self.groupBox_pasajero.setStyleSheet("\n"
"QLabel{\n"
"    font: bold 15px;\n"
"    background-color: rgb(204, 204, 204);\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color: rgb(255,255,255);\n"
"    font: 12pt \"Calibri\";\n"
"    border-width: 2px;\n"
"    border-style: solid;\n"
"    border-color: rgb(131, 131, 131)\n"
"}\n"
"\n"
"QLabel:lbl_nro_pasajero{\n"
"    background-color: rgb(255,255,255);\n"
"    font: 12pt \"Calibri\";\n"
"    border-width: 2px;\n"
"    border-style: solid;\n"
"    border-color: rgb(131, 131, 131)\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(255,255,255);\n"
"    font: 12pt \"Calibri\";\n"
"    border-width: 2px;\n"
"    border-style: solid;\n"
"    border-color: rgb(131, 131, 131);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(153, 142, 140);\n"
"    font: 75 italic 12pt \"Calibri\";\n"
"    border-width: 2px;\n"
"    border-style: solid;\n"
"    border-color: rgb(131, 131, 131);\n"
"    border-radius: 4px;\n"
"}")
        self.groupBox_pasajero.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_pasajero.setFlat(True)
        self.groupBox_pasajero.setCheckable(False)
        self.groupBox_pasajero.setObjectName("groupBox_pasajero")
        self.label = QtWidgets.QLabel(self.groupBox_pasajero)
        self.label.setGeometry(QtCore.QRect(371, 72, 72, 18))
        self.label.setObjectName("label")
        self.lineEdit_nombre = QtWidgets.QLineEdit(self.groupBox_pasajero)
        self.lineEdit_nombre.setGeometry(QtCore.QRect(450, 70, 391, 25))
        self.lineEdit_nombre.setCursorPosition(0)
        self.lineEdit_nombre.setObjectName("lineEdit_nombre")
        self.label_2 = QtWidgets.QLabel(self.groupBox_pasajero)
        self.label_2.setGeometry(QtCore.QRect(61, 71, 104, 18))
        self.label_2.setObjectName("label_2")
        self.lineEdit_dni = QtWidgets.QLineEdit(self.groupBox_pasajero)
        self.lineEdit_dni.setGeometry(QtCore.QRect(180, 69, 137, 25))
        self.lineEdit_dni.setObjectName("lineEdit_dni")
        self.label_3 = QtWidgets.QLabel(self.groupBox_pasajero)
        self.label_3.setGeometry(QtCore.QRect(60, 120, 94, 18))
        self.label_3.setObjectName("label_3")
        self.lineEdit_localidad = QtWidgets.QLineEdit(self.groupBox_pasajero)
        self.lineEdit_localidad.setGeometry(QtCore.QRect(159, 118, 241, 25))
        self.lineEdit_localidad.setCursorPosition(0)
        self.lineEdit_localidad.setObjectName("lineEdit_localidad")
        self.label_4 = QtWidgets.QLabel(self.groupBox_pasajero)
        self.label_4.setGeometry(QtCore.QRect(460, 120, 94, 18))
        self.label_4.setObjectName("label_4")
        self.lineEdit_provincia = QtWidgets.QLineEdit(self.groupBox_pasajero)
        self.lineEdit_provincia.setGeometry(QtCore.QRect(559, 118, 281, 25))
        self.lineEdit_provincia.setCursorPosition(0)
        self.lineEdit_provincia.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_provincia.setObjectName("lineEdit_provincia")
        self.label_5 = QtWidgets.QLabel(self.groupBox_pasajero)
        self.label_5.setGeometry(QtCore.QRect(61, 163, 73, 18))
        self.label_5.setObjectName("label_5")
        self.lineEdit_patente = QtWidgets.QLineEdit(self.groupBox_pasajero)
        self.lineEdit_patente.setGeometry(QtCore.QRect(140, 160, 137, 25))
        self.lineEdit_patente.setCursorPosition(0)
        self.lineEdit_patente.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_patente.setObjectName("lineEdit_patente")
        self.label_6 = QtWidgets.QLabel(self.groupBox_pasajero)
        self.label_6.setGeometry(QtCore.QRect(61, 211, 53, 18))
        self.label_6.setObjectName("label_6")
        self.lineEdit_email = QtWidgets.QLineEdit(self.groupBox_pasajero)
        self.lineEdit_email.setGeometry(QtCore.QRect(120, 210, 371, 25))
        self.lineEdit_email.setCursorPosition(0)
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.label_7 = QtWidgets.QLabel(self.groupBox_pasajero)
        self.label_7.setGeometry(QtCore.QRect(311, 161, 84, 18))
        self.label_7.setObjectName("label_7")
        self.lineEdit_vehiculo = QtWidgets.QLineEdit(self.groupBox_pasajero)
        self.lineEdit_vehiculo.setGeometry(QtCore.QRect(400, 160, 211, 25))
        self.lineEdit_vehiculo.setCursorPosition(0)
        self.lineEdit_vehiculo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_vehiculo.setObjectName("lineEdit_vehiculo")
        self.label_8 = QtWidgets.QLabel(self.groupBox_pasajero)
        self.label_8.setGeometry(QtCore.QRect(531, 212, 86, 18))
        self.label_8.setObjectName("label_8")
        self.lineEdit_telefono = QtWidgets.QLineEdit(self.groupBox_pasajero)
        self.lineEdit_telefono.setGeometry(QtCore.QRect(620, 210, 137, 25))
        self.lineEdit_telefono.setCursorPosition(0)
        self.lineEdit_telefono.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_telefono.setObjectName("lineEdit_telefono")
        self.btn_cancelar = QtWidgets.QPushButton(self.groupBox_pasajero)
        self.btn_cancelar.setGeometry(QtCore.QRect(490, 260, 101, 28))
        self.btn_cancelar.setObjectName("btn_cancelar")
        self.btn_siguiente = QtWidgets.QPushButton(self.groupBox_pasajero)
        self.btn_siguiente.setGeometry(QtCore.QRect(600, 260, 111, 28))
        self.btn_siguiente.setObjectName("btn_siguiente")
        self.btn_finalizar = QtWidgets.QPushButton(self.groupBox_pasajero)
        self.btn_finalizar.setGeometry(QtCore.QRect(780, 260, 101, 28))
        self.btn_finalizar.setObjectName("btn_finalizar")
        self.tabla_mostrar_pasajeros = QtWidgets.QTableWidget(self.frame_registro)
        self.tabla_mostrar_pasajeros.setGeometry(QtCore.QRect(80, 450, 1011, 261))
        self.tabla_mostrar_pasajeros.setMaximumSize(QtCore.QSize(1151, 16777215))
        self.tabla_mostrar_pasajeros.setObjectName("tabla_mostrar_pasajeros")
        self.tabla_mostrar_pasajeros.setColumnCount(8)
        self.tabla_mostrar_pasajeros.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_mostrar_pasajeros.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_mostrar_pasajeros.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_mostrar_pasajeros.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_mostrar_pasajeros.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_mostrar_pasajeros.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_mostrar_pasajeros.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_mostrar_pasajeros.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_mostrar_pasajeros.setHorizontalHeaderItem(7, item)
        self.horizontalLayout.addWidget(self.frame_registro)
        MainWindow.setCentralWidget(self.centralwidget)
        self.label.setBuddy(self.lineEdit_nombre)
        self.label_2.setBuddy(self.lineEdit_dni)
        self.label_3.setBuddy(self.lineEdit_localidad)
        self.label_4.setBuddy(self.lineEdit_provincia)
        self.label_5.setBuddy(self.lineEdit_patente)
        self.label_6.setBuddy(self.lineEdit_email)
        self.label_7.setBuddy(self.lineEdit_vehiculo)
        self.label_8.setBuddy(self.lineEdit_telefono)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_dni, self.lineEdit_nombre)
        MainWindow.setTabOrder(self.lineEdit_nombre, self.lineEdit_localidad)
        MainWindow.setTabOrder(self.lineEdit_localidad, self.lineEdit_provincia)
        MainWindow.setTabOrder(self.lineEdit_provincia, self.lineEdit_patente)
        MainWindow.setTabOrder(self.lineEdit_patente, self.lineEdit_vehiculo)
        MainWindow.setTabOrder(self.lineEdit_vehiculo, self.lineEdit_email)
        MainWindow.setTabOrder(self.lineEdit_email, self.lineEdit_telefono)
        MainWindow.setTabOrder(self.lineEdit_telefono, self.btn_cancelar)
        MainWindow.setTabOrder(self.btn_cancelar, self.btn_siguiente)
        MainWindow.setTabOrder(self.btn_siguiente, self.btn_finalizar)
        MainWindow.setTabOrder(self.btn_finalizar, self.tabla_mostrar_pasajeros)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_pasajero.setTitle(_translate("MainWindow", "Registro de pasajeros"))
        self.label.setText(_translate("MainWindow", "NOMBRE:"))
        self.label_2.setText(_translate("MainWindow", "DOCUMENTO:"))
        self.label_3.setText(_translate("MainWindow", "LOCALIDAD:"))
        self.label_4.setText(_translate("MainWindow", "PROVINCIA:"))
        self.label_5.setText(_translate("MainWindow", "PATENTE:"))
        self.label_6.setText(_translate("MainWindow", "EMAIL:"))
        self.label_7.setText(_translate("MainWindow", "VEHICULO:"))
        self.label_8.setText(_translate("MainWindow", "TELEFONO:"))
        self.btn_cancelar.setText(_translate("MainWindow", "CANCELAR"))
        self.btn_siguiente.setText(_translate("MainWindow", "SIGUIENTE"))
        self.btn_finalizar.setText(_translate("MainWindow", "FINALIZAR"))
        item = self.tabla_mostrar_pasajeros.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "DOCUMENTO"))
        item = self.tabla_mostrar_pasajeros.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NOMBRE"))
        item = self.tabla_mostrar_pasajeros.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "LOCALIDAD"))
        item = self.tabla_mostrar_pasajeros.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "PROVINCIA"))
        item = self.tabla_mostrar_pasajeros.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "VEHICULO"))
        item = self.tabla_mostrar_pasajeros.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "PATENTE"))
        item = self.tabla_mostrar_pasajeros.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "EMAIL"))
        item = self.tabla_mostrar_pasajeros.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "TELEFONO"))
