# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Usuario\Desktop\PROYECTOS\AppRes V 1.0\ui_archivos\registro_prueba.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("QMainWindow{\n"
"    \n"
"    background-color: rgb(129, 255, 182);\n"
"}\n"
"\n"
"QGroupBox{\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #E0E0E0, stop: 1 #FFFFFF);\n"
"    border: 2px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 1ex; /* leave space at the top for the title */\n"
"}\n"
"\n"
"QLabel{\n"
"    color:rgb(53, 123, 158);    \n"
"    font: Italic 12pt \"Calibri\";\n"
"}\n"
"\n"
"QLabel#lbl_nro_hab_1{\n"
"    \n"
"    background-color: rgb(108, 108, 108);\n"
"    border: 1px solid;\n"
"    border-color: rgb(0,0,0);\n"
"    color:rgb(255,255,255);    \n"
"    font: Bold 12pt \"Arial\";\n"
"}\n"
"QLabel#lbl_nro_hab_2{\n"
"    \n"
"    background-color: rgb(108, 108, 108);\n"
"    border: 1px solid;\n"
"    border-color: rgb(0,0,0);\n"
"    color:rgb(255,255,255);    \n"
"    font: Bold 12pt \"Arial\";\n"
"}\n"
"QLabel#lbl_nro_hab_3{\n"
"    \n"
"    background-color: rgb(108, 108, 108);\n"
"    border: 1px solid;\n"
"    border-color: rgb(0,0,0);\n"
"    color:rgb(255,255,255);    \n"
"    font: Bold 12pt \"Arial\";\n"
"}\n"
"QLabel#lbl_nro_hab_4{\n"
"    \n"
"    background-color: rgb(108, 108, 108);\n"
"    border: 1px solid;\n"
"    border-color: rgb(0,0,0);\n"
"    color:rgb(255,255,255);    \n"
"    font: Bold 12pt \"Arial\";\n"
"}\n"
"\n"
"QLabel#lbl_referencia_1{\n"
"    \n"
"    background-color: rgb(158, 158, 158);\n"
"    border: 1px solid;\n"
"    border-color: rgb(0,0,0);\n"
"    color:rgb(0,0,0);    \n"
"    font: Bold 12pt \"Arial\";\n"
"}\n"
"QLabel#lbl_referencia_2{\n"
"    \n"
"    background-color: rgb(158, 158, 158);\n"
"    border: 1px solid;\n"
"    border-color: rgb(0,0,0);\n"
"    color:rgb(0,0,0);    \n"
"    font: Bold 12pt \"Arial\";\n"
"}\n"
"QLabel#lbl_referencia_3{\n"
"    \n"
"    background-color: rgb(158, 158, 158);\n"
"    border: 1px solid;\n"
"    border-color: rgb(0,0,0);\n"
"    color:rgb(0,0,0);    \n"
"    font: Bold 12pt \"Arial\";\n"
"}\n"
"QLabel#lbl_referencia_4{\n"
"    \n"
"    background-color: rgb(158, 158, 158);\n"
"    border: 1px solid;\n"
"    border-color: rgb(0,0,0);\n"
"    color:rgb(0,0,0);    \n"
"    font: Bold 12pt \"Arial\";\n"
"}\n"
"\n"
"QLabel#lbl_estado_1{\n"
"    \n"
"    background-color: rgb(158, 158, 158);\n"
"    border: 1px solid;\n"
"    border-color: rgb(0,0,0);\n"
"    color:rgb(255,255,255);    \n"
"    font: Bold 12pt \"Arial\";\n"
"}\n"
"QLabel#lbl_estado_2{\n"
"    \n"
"    background-color: rgb(158, 158, 158);\n"
"    border: 1px solid;\n"
"    border-color: rgb(0,0,0);\n"
"    color:rgb(255,255,255);    \n"
"    font: Bold 12pt \"Arial\";\n"
"}\n"
"QLabel#lbl_estado_3{\n"
"    \n"
"    background-color: rgb(158, 158, 158);\n"
"    border: 1px solid;\n"
"    border-color: rgb(0,0,0);\n"
"    color:rgb(255,255,255);    \n"
"    font: Bold 12pt \"Arial\";\n"
"}\n"
"QLabel#lbl_estado_4{\n"
"    \n"
"    background-color: rgb(158, 158, 158);\n"
"    border: 1px solid;\n"
"    border-color: rgb(0,0,0);\n"
"    color:rgb(255,255,255);    \n"
"    font: Bold 12pt \"Arial\";\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(58, 135, 173);\n"
"    border: 2px solid gray;\n"
"    border-radius: 9px;    \n"
"    color:rgb(255,255,255);    \n"
"    font: Bold 9.5pt \"Calibri\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(83, 193, 247);\n"
"    border: 2px solid black;\n"
"    border-radius: 9px;    \n"
"    color:rgb(255,255,255);    \n"
"    font: Bold 10pt \"Calibri\";\n"
"}\n"
"\n"
"QPushButton:!enable{\n"
"    background-color: rgb(rgb(167, 210, 249));\n"
"    border: 2px solid gray;\n"
"    border-radius: 9px;    \n"
"    color:rgb(255,255,255);    \n"
"    font: Bold 11pt \"Calibri\";\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(90, 90, 261, 181))
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.btn_ocupa_libera = QtWidgets.QPushButton(self.groupBox)
        self.btn_ocupa_libera.setGeometry(QtCore.QRect(180, 140, 71, 28))
        self.btn_ocupa_libera.setText("")
        self.btn_ocupa_libera.setObjectName("btn_ocupa_libera")
        self.lbl_nro_hab_1 = QtWidgets.QLabel(self.groupBox)
        self.lbl_nro_hab_1.setGeometry(QtCore.QRect(90, 10, 161, 31))
        self.lbl_nro_hab_1.setText("")
        self.lbl_nro_hab_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_nro_hab_1.setObjectName("lbl_nro_hab_1")
        self.lbl_referencia_1 = QtWidgets.QLabel(self.groupBox)
        self.lbl_referencia_1.setGeometry(QtCore.QRect(20, 100, 221, 25))
        self.lbl_referencia_1.setText("")
        self.lbl_referencia_1.setObjectName("lbl_referencia_1")
        self.lbl_estado_1 = QtWidgets.QLabel(self.groupBox)
        self.lbl_estado_1.setGeometry(QtCore.QRect(110, 58, 131, 25))
        self.lbl_estado_1.setText("")
        self.lbl_estado_1.setObjectName("lbl_estado_1")
        self.btn_reserva = QtWidgets.QPushButton(self.groupBox)
        self.btn_reserva.setGeometry(QtCore.QRect(10, 140, 81, 28))
        self.btn_reserva.setText("")
        self.btn_reserva.setObjectName("btn_reserva")
        self.btn_repara = QtWidgets.QPushButton(self.groupBox)
        self.btn_repara.setGeometry(QtCore.QRect(100, 140, 71, 28))
        self.btn_repara.setText("")
        self.btn_repara.setObjectName("btn_repara")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(40, 60, 61, 16))
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(410, 90, 261, 181))
        self.groupBox_2.setObjectName("groupBox_2")
        self.btn_ocupa_libera_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_ocupa_libera_2.setGeometry(QtCore.QRect(174, 140, 81, 28))
        self.btn_ocupa_libera_2.setText("")
        self.btn_ocupa_libera_2.setObjectName("btn_ocupa_libera_2")
        self.lbl_nro_hab_2 = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_nro_hab_2.setGeometry(QtCore.QRect(90, 10, 161, 31))
        self.lbl_nro_hab_2.setText("")
        self.lbl_nro_hab_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_nro_hab_2.setObjectName("lbl_nro_hab_2")
        self.lbl_referencia_2 = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_referencia_2.setGeometry(QtCore.QRect(20, 100, 221, 25))
        self.lbl_referencia_2.setText("")
        self.lbl_referencia_2.setObjectName("lbl_referencia_2")
        self.lbl_estado_2 = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_estado_2.setGeometry(QtCore.QRect(120, 57, 121, 25))
        self.lbl_estado_2.setText("")
        self.lbl_estado_2.setObjectName("lbl_estado_2")
        self.btn_repara_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_repara_2.setGeometry(QtCore.QRect(98, 140, 71, 28))
        self.btn_repara_2.setText("")
        self.btn_repara_2.setObjectName("btn_repara_2")
        self.btn_reserva_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_reserva_2.setGeometry(QtCore.QRect(10, 140, 81, 28))
        self.btn_reserva_2.setText("")
        self.btn_reserva_2.setObjectName("btn_reserva_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(50, 60, 61, 16))
        self.label_2.setObjectName("label_2")
        self.boton_salir = QtWidgets.QPushButton(self.centralwidget)
        self.boton_salir.setGeometry(QtCore.QRect(590, 520, 191, 41))
        self.boton_salir.setObjectName("boton_salir")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(90, 300, 261, 181))
        self.groupBox_3.setObjectName("groupBox_3")
        self.btn_ocupa_libera_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_ocupa_libera_3.setGeometry(QtCore.QRect(175, 140, 81, 28))
        self.btn_ocupa_libera_3.setText("")
        self.btn_ocupa_libera_3.setObjectName("btn_ocupa_libera_3")
        self.lbl_nro_hab_3 = QtWidgets.QLabel(self.groupBox_3)
        self.lbl_nro_hab_3.setGeometry(QtCore.QRect(90, 10, 161, 31))
        self.lbl_nro_hab_3.setText("")
        self.lbl_nro_hab_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_nro_hab_3.setObjectName("lbl_nro_hab_3")
        self.lbl_referencia_3 = QtWidgets.QLabel(self.groupBox_3)
        self.lbl_referencia_3.setGeometry(QtCore.QRect(20, 100, 221, 25))
        self.lbl_referencia_3.setText("")
        self.lbl_referencia_3.setObjectName("lbl_referencia_3")
        self.lbl_estado_3 = QtWidgets.QLabel(self.groupBox_3)
        self.lbl_estado_3.setGeometry(QtCore.QRect(120, 58, 121, 25))
        self.lbl_estado_3.setText("")
        self.lbl_estado_3.setObjectName("lbl_estado_3")
        self.btn_repara_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_repara_3.setGeometry(QtCore.QRect(100, 140, 71, 28))
        self.btn_repara_3.setText("")
        self.btn_repara_3.setObjectName("btn_repara_3")
        self.btn_reserva_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_reserva_3.setGeometry(QtCore.QRect(10, 140, 81, 28))
        self.btn_reserva_3.setText("")
        self.btn_reserva_3.setObjectName("btn_reserva_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(50, 60, 61, 16))
        self.label_3.setObjectName("label_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(410, 300, 261, 181))
        self.groupBox_4.setObjectName("groupBox_4")
        self.btn_ocupa_libera_4 = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_ocupa_libera_4.setGeometry(QtCore.QRect(173, 140, 81, 28))
        self.btn_ocupa_libera_4.setText("")
        self.btn_ocupa_libera_4.setObjectName("btn_ocupa_libera_4")
        self.lbl_nro_hab_4 = QtWidgets.QLabel(self.groupBox_4)
        self.lbl_nro_hab_4.setGeometry(QtCore.QRect(90, 10, 161, 31))
        self.lbl_nro_hab_4.setText("")
        self.lbl_nro_hab_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_nro_hab_4.setObjectName("lbl_nro_hab_4")
        self.lbl_referencia_4 = QtWidgets.QLabel(self.groupBox_4)
        self.lbl_referencia_4.setGeometry(QtCore.QRect(20, 100, 221, 25))
        self.lbl_referencia_4.setText("")
        self.lbl_referencia_4.setObjectName("lbl_referencia_4")
        self.lbl_estado_4 = QtWidgets.QLabel(self.groupBox_4)
        self.lbl_estado_4.setGeometry(QtCore.QRect(120, 58, 121, 25))
        self.lbl_estado_4.setText("")
        self.lbl_estado_4.setObjectName("lbl_estado_4")
        self.btn_repara_4 = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_repara_4.setGeometry(QtCore.QRect(97, 140, 71, 28))
        self.btn_repara_4.setText("")
        self.btn_repara_4.setObjectName("btn_repara_4")
        self.btn_reserva_4 = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_reserva_4.setGeometry(QtCore.QRect(10, 140, 81, 28))
        self.btn_reserva_4.setText("")
        self.btn_reserva_4.setObjectName("btn_reserva_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(50, 60, 61, 16))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.boton_salir.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Registro de pasajeros"))
        self.groupBox.setTitle(_translate("MainWindow", "HABITACION"))
        self.label.setText(_translate("MainWindow", "Estado:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "HABITACION"))
        self.label_2.setText(_translate("MainWindow", "Estado:"))
        self.boton_salir.setText(_translate("MainWindow", "FINALIZAR"))
        self.groupBox_3.setTitle(_translate("MainWindow", "HABITACION"))
        self.label_3.setText(_translate("MainWindow", "Estado:"))
        self.groupBox_4.setTitle(_translate("MainWindow", "HABITACION"))
        self.label_4.setText(_translate("MainWindow", "Estado:"))
