# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Usuario\Desktop\PROYECTOS\AppRes V 1.0\ui_archivos\ventana_registro_pasajeros.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ventana_registro_pasajeros(object):
    def setupUi(self, ventana_registro_pasajeros):
        ventana_registro_pasajeros.setObjectName("ventana_registro_pasajeros")
        ventana_registro_pasajeros.resize(1177, 794)
        ventana_registro_pasajeros.setStyleSheet("QGroupBox{\n"
"    border-color: rgb(0,0,0)\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(ventana_registro_pasajeros)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 32, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(102, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.groupBox_pasajero = QtWidgets.QGroupBox(ventana_registro_pasajeros)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_pasajero.sizePolicy().hasHeightForWidth())
        self.groupBox_pasajero.setSizePolicy(sizePolicy)
        self.groupBox_pasajero.setMinimumSize(QtCore.QSize(920, 310))
        self.groupBox_pasajero.setMaximumSize(QtCore.QSize(920, 310))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_pasajero.setFont(font)
        self.groupBox_pasajero.setStyleSheet("QGroupBox{\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(131, 131, 131);\n"
"    border-radius: 5px;\n"
"}\n"
"QLabel{\n"
"    font: bold 15px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLabel#lbl_mensaje2{\n"
"    color:rgb(255, 0, 0);\n"
"    font: 5pt \"Calibri\";\n"
"\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color: rgb(255,255,255);\n"
"    font: 12pt \"Calibri\";\n"
"    border-width: 2px;\n"
"    border-top-color: rgb(0, 0, 0);\n"
"    border-left-color: rgb(0, 0, 0);\n"
"    border-right-color: rgb(255,255,255);    \n"
"    border-bottom-color: rgb(255,255,255);\n"
"    border-style: solid;\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(255,255,255);\n"
"    font: 12pt \"Calibri\";\n"
"    border-width: 2px;\n"
"    border-style: solid;\n"
"    border-color: rgb(131, 131, 131);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(153, 142, 140);\n"
"    font: 75 italic 12pt \"Calibri\";\n"
"    border-width: 2px;\n"
"    border-style: solid;\n"
"    border-color: rgb(131, 131, 131);\n"
"    border-radius: 4px;\n"
"}")
        self.groupBox_pasajero.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_pasajero.setFlat(True)
        self.groupBox_pasajero.setCheckable(False)
        self.groupBox_pasajero.setObjectName("groupBox_pasajero")
        self.label = QtWidgets.QLabel(self.groupBox_pasajero)
        self.label.setGeometry(QtCore.QRect(351, 62, 72, 18))
        self.label.setObjectName("label")
        self.lineEdit_nombre = QtWidgets.QLineEdit(self.groupBox_pasajero)
        self.lineEdit_nombre.setGeometry(QtCore.QRect(430, 60, 391, 25))
        self.lineEdit_nombre.setMaxLength(50)
        self.lineEdit_nombre.setCursorPosition(0)
        self.lineEdit_nombre.setObjectName("lineEdit_nombre")
        self.label_2 = QtWidgets.QLabel(self.groupBox_pasajero)
        self.label_2.setGeometry(QtCore.QRect(41, 62, 104, 18))
        self.label_2.setObjectName("label_2")
        self.lineEdit_dni = QtWidgets.QLineEdit(self.groupBox_pasajero)
        self.lineEdit_dni.setGeometry(QtCore.QRect(160, 60, 137, 25))
        self.lineEdit_dni.setMaxLength(8)
        self.lineEdit_dni.setObjectName("lineEdit_dni")
        self.label_3 = QtWidgets.QLabel(self.groupBox_pasajero)
        self.label_3.setGeometry(QtCore.QRect(41, 122, 94, 18))
        self.label_3.setObjectName("label_3")
        self.lineEdit_localidad = QtWidgets.QLineEdit(self.groupBox_pasajero)
        self.lineEdit_localidad.setGeometry(QtCore.QRect(140, 120, 241, 25))
        self.lineEdit_localidad.setMaxLength(30)
        self.lineEdit_localidad.setCursorPosition(0)
        self.lineEdit_localidad.setObjectName("lineEdit_localidad")
        self.label_4 = QtWidgets.QLabel(self.groupBox_pasajero)
        self.label_4.setGeometry(QtCore.QRect(431, 122, 94, 18))
        self.label_4.setObjectName("label_4")
        self.lineEdit_provincia = QtWidgets.QLineEdit(self.groupBox_pasajero)
        self.lineEdit_provincia.setGeometry(QtCore.QRect(530, 120, 281, 25))
        self.lineEdit_provincia.setMaxLength(30)
        self.lineEdit_provincia.setCursorPosition(0)
        self.lineEdit_provincia.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_provincia.setObjectName("lineEdit_provincia")
        self.label_5 = QtWidgets.QLabel(self.groupBox_pasajero)
        self.label_5.setGeometry(QtCore.QRect(41, 173, 73, 18))
        self.label_5.setObjectName("label_5")
        self.lineEdit_patente = QtWidgets.QLineEdit(self.groupBox_pasajero)
        self.lineEdit_patente.setGeometry(QtCore.QRect(120, 170, 137, 25))
        self.lineEdit_patente.setMaxLength(8)
        self.lineEdit_patente.setCursorPosition(0)
        self.lineEdit_patente.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_patente.setObjectName("lineEdit_patente")
        self.label_6 = QtWidgets.QLabel(self.groupBox_pasajero)
        self.label_6.setGeometry(QtCore.QRect(41, 221, 53, 18))
        self.label_6.setObjectName("label_6")
        self.lineEdit_email = QtWidgets.QLineEdit(self.groupBox_pasajero)
        self.lineEdit_email.setGeometry(QtCore.QRect(100, 220, 371, 25))
        self.lineEdit_email.setMaxLength(50)
        self.lineEdit_email.setCursorPosition(0)
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.label_7 = QtWidgets.QLabel(self.groupBox_pasajero)
        self.label_7.setGeometry(QtCore.QRect(311, 171, 84, 18))
        self.label_7.setObjectName("label_7")
        self.lineEdit_vehiculo = QtWidgets.QLineEdit(self.groupBox_pasajero)
        self.lineEdit_vehiculo.setGeometry(QtCore.QRect(400, 170, 211, 25))
        self.lineEdit_vehiculo.setMaxLength(30)
        self.lineEdit_vehiculo.setCursorPosition(0)
        self.lineEdit_vehiculo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_vehiculo.setObjectName("lineEdit_vehiculo")
        self.label_8 = QtWidgets.QLabel(self.groupBox_pasajero)
        self.label_8.setGeometry(QtCore.QRect(501, 222, 86, 18))
        self.label_8.setObjectName("label_8")
        self.lineEdit_telefono = QtWidgets.QLineEdit(self.groupBox_pasajero)
        self.lineEdit_telefono.setGeometry(QtCore.QRect(590, 220, 137, 25))
        self.lineEdit_telefono.setMaxLength(15)
        self.lineEdit_telefono.setCursorPosition(0)
        self.lineEdit_telefono.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_telefono.setObjectName("lineEdit_telefono")
        self.btn_cancelar = QtWidgets.QPushButton(self.groupBox_pasajero)
        self.btn_cancelar.setGeometry(QtCore.QRect(500, 270, 101, 28))
        self.btn_cancelar.setObjectName("btn_cancelar")
        self.btn_siguiente = QtWidgets.QPushButton(self.groupBox_pasajero)
        self.btn_siguiente.setGeometry(QtCore.QRect(610, 270, 111, 28))
        self.btn_siguiente.setObjectName("btn_siguiente")
        self.btn_finalizar = QtWidgets.QPushButton(self.groupBox_pasajero)
        self.btn_finalizar.setGeometry(QtCore.QRect(790, 270, 101, 28))
        self.btn_finalizar.setObjectName("btn_finalizar")
        self.lbl_mensaje = QtWidgets.QLabel(self.groupBox_pasajero)
        self.lbl_mensaje.setGeometry(QtCore.QRect(150, 90, 161, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.lbl_mensaje.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lbl_mensaje.setFont(font)
        self.lbl_mensaje.setObjectName("lbl_mensaje")
        self.lbl_mensaje_2 = QtWidgets.QLabel(self.groupBox_pasajero)
        self.lbl_mensaje_2.setGeometry(QtCore.QRect(430, 90, 161, 16))
        self.lbl_mensaje_2.setObjectName("lbl_mensaje_2")
        self.horizontalLayout.addWidget(self.groupBox_pasajero)
        spacerItem2 = QtWidgets.QSpacerItem(112, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 31, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.tabla_mostrar_pasajeros = QtWidgets.QTableWidget(ventana_registro_pasajeros)
        self.tabla_mostrar_pasajeros.setMinimumSize(QtCore.QSize(1149, 370))
        self.tabla_mostrar_pasajeros.setMaximumSize(QtCore.QSize(1149, 16777215))
        self.tabla_mostrar_pasajeros.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tabla_mostrar_pasajeros.setShowGrid(True)
        self.tabla_mostrar_pasajeros.setRowCount(0)
        self.tabla_mostrar_pasajeros.setObjectName("tabla_mostrar_pasajeros")
        self.tabla_mostrar_pasajeros.setColumnCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_mostrar_pasajeros.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_mostrar_pasajeros.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_mostrar_pasajeros.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_mostrar_pasajeros.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_mostrar_pasajeros.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_mostrar_pasajeros.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_mostrar_pasajeros.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_mostrar_pasajeros.setHorizontalHeaderItem(7, item)
        self.tabla_mostrar_pasajeros.horizontalHeader().setDefaultSectionSize(141)
        self.tabla_mostrar_pasajeros.horizontalHeader().setHighlightSections(True)
        self.tabla_mostrar_pasajeros.horizontalHeader().setMinimumSectionSize(141)
        self.tabla_mostrar_pasajeros.horizontalHeader().setSortIndicatorShown(False)
        self.tabla_mostrar_pasajeros.horizontalHeader().setStretchLastSection(False)
        self.tabla_mostrar_pasajeros.verticalHeader().setVisible(True)
        self.tabla_mostrar_pasajeros.verticalHeader().setCascadingSectionResizes(False)
        self.verticalLayout.addWidget(self.tabla_mostrar_pasajeros)
        self.label.setBuddy(self.lineEdit_nombre)
        self.label_2.setBuddy(self.lineEdit_dni)
        self.label_3.setBuddy(self.lineEdit_localidad)
        self.label_4.setBuddy(self.lineEdit_provincia)
        self.label_5.setBuddy(self.lineEdit_patente)
        self.label_6.setBuddy(self.lineEdit_email)
        self.label_7.setBuddy(self.lineEdit_vehiculo)
        self.label_8.setBuddy(self.lineEdit_telefono)

        self.retranslateUi(ventana_registro_pasajeros)
        QtCore.QMetaObject.connectSlotsByName(ventana_registro_pasajeros)
        ventana_registro_pasajeros.setTabOrder(self.lineEdit_dni, self.lineEdit_nombre)
        ventana_registro_pasajeros.setTabOrder(self.lineEdit_nombre, self.lineEdit_localidad)
        ventana_registro_pasajeros.setTabOrder(self.lineEdit_localidad, self.lineEdit_provincia)
        ventana_registro_pasajeros.setTabOrder(self.lineEdit_provincia, self.lineEdit_patente)
        ventana_registro_pasajeros.setTabOrder(self.lineEdit_patente, self.lineEdit_vehiculo)
        ventana_registro_pasajeros.setTabOrder(self.lineEdit_vehiculo, self.lineEdit_email)
        ventana_registro_pasajeros.setTabOrder(self.lineEdit_email, self.lineEdit_telefono)
        ventana_registro_pasajeros.setTabOrder(self.lineEdit_telefono, self.btn_cancelar)
        ventana_registro_pasajeros.setTabOrder(self.btn_cancelar, self.btn_siguiente)
        ventana_registro_pasajeros.setTabOrder(self.btn_siguiente, self.btn_finalizar)
        ventana_registro_pasajeros.setTabOrder(self.btn_finalizar, self.tabla_mostrar_pasajeros)

    def retranslateUi(self, ventana_registro_pasajeros):
        _translate = QtCore.QCoreApplication.translate
        ventana_registro_pasajeros.setWindowTitle(_translate("ventana_registro_pasajeros", "Dialog"))
        self.groupBox_pasajero.setTitle(_translate("ventana_registro_pasajeros", "Registro de pasajeros"))
        self.label.setText(_translate("ventana_registro_pasajeros", "NOMBRE:"))
        self.label_2.setText(_translate("ventana_registro_pasajeros", "DOCUMENTO:"))
        self.label_3.setText(_translate("ventana_registro_pasajeros", "LOCALIDAD:"))
        self.label_4.setText(_translate("ventana_registro_pasajeros", "PROVINCIA:"))
        self.label_5.setText(_translate("ventana_registro_pasajeros", "PATENTE:"))
        self.label_6.setText(_translate("ventana_registro_pasajeros", "EMAIL:"))
        self.label_7.setText(_translate("ventana_registro_pasajeros", "VEHICULO:"))
        self.label_8.setText(_translate("ventana_registro_pasajeros", "TELEFONO:"))
        self.btn_cancelar.setText(_translate("ventana_registro_pasajeros", "CANCELAR"))
        self.btn_siguiente.setText(_translate("ventana_registro_pasajeros", "SIGUIENTE"))
        self.btn_finalizar.setText(_translate("ventana_registro_pasajeros", "FINALIZAR"))
        self.lbl_mensaje.setText(_translate("ventana_registro_pasajeros", "*Campo Obligatorio"))
        self.lbl_mensaje_2.setText(_translate("ventana_registro_pasajeros", "*Campo Obligatorio"))
        item = self.tabla_mostrar_pasajeros.horizontalHeaderItem(0)
        item.setText(_translate("ventana_registro_pasajeros", "DOCUMENTO"))
        item = self.tabla_mostrar_pasajeros.horizontalHeaderItem(1)
        item.setText(_translate("ventana_registro_pasajeros", "NOMBRE"))
        item = self.tabla_mostrar_pasajeros.horizontalHeaderItem(2)
        item.setText(_translate("ventana_registro_pasajeros", "LOCALIDAD"))
        item = self.tabla_mostrar_pasajeros.horizontalHeaderItem(3)
        item.setText(_translate("ventana_registro_pasajeros", "PROVINCIA"))
        item = self.tabla_mostrar_pasajeros.horizontalHeaderItem(4)
        item.setText(_translate("ventana_registro_pasajeros", "VEHICULO"))
        item = self.tabla_mostrar_pasajeros.horizontalHeaderItem(5)
        item.setText(_translate("ventana_registro_pasajeros", "PATENTE"))
        item = self.tabla_mostrar_pasajeros.horizontalHeaderItem(6)
        item.setText(_translate("ventana_registro_pasajeros", "EMAIL"))
        item = self.tabla_mostrar_pasajeros.horizontalHeaderItem(7)
        item.setText(_translate("ventana_registro_pasajeros", "TELEFONO"))
