# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Usuario\Desktop\PROYECTOS\AppRes V 1.0\ui_archivos\varias_paginas.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from tkinter import CENTER
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn1 = QtWidgets.QPushButton(self.frame_2)
        self.btn1.setMinimumSize(QtCore.QSize(0, 80))
        self.btn1.setObjectName("btn1")
        self.horizontalLayout.addWidget(self.btn1)
        self.btn2 = QtWidgets.QPushButton(self.frame_2)
        self.btn2.setMinimumSize(QtCore.QSize(0, 80))
        self.btn2.setObjectName("btn2")
        self.horizontalLayout.addWidget(self.btn2)
        self.btn3 = QtWidgets.QPushButton(self.frame_2)
        self.btn3.setMinimumSize(QtCore.QSize(0, 80))
        self.btn3.setObjectName("btn3")
        self.horizontalLayout.addWidget(self.btn3)
        self.btn4 = QtWidgets.QPushButton(self.frame_2)
        self.btn4.setMinimumSize(QtCore.QSize(0, 80))
        self.btn4.setObjectName("btn4")
        self.horizontalLayout.addWidget(self.btn4)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QLabel{\n"
"    font: 15pt Bold \"Arial\";\n"
"}\n"
"QLineEdit{\n"
"    font: 15pt Bold \"Arial\";\n"
"}\n"
"QPushButton{\n"
"    font: 15pt Bold \"Arial\";\n"
"}\n"
"QFrame{\n"
"    \n"
"    background-color: rgb(253, 253, 126);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        self.label = QtWidgets.QLabel(self.page1)
        self.label.setGeometry(QtCore.QRect(40, 100, 181, 41))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.page1)
        self.lineEdit.setGeometry(QtCore.QRect(240, 100, 281, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.page1)
        self.pushButton.setGeometry(QtCore.QRect(250, 180, 271, 51))
        self.pushButton.setObjectName("pushButton")
        self.stackedWidget.addWidget(self.page1)
        self.page2 = QtWidgets.QWidget()
        self.page2.setObjectName("page2")
        self.label_2 = QtWidgets.QLabel(self.page2)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 271, 81))
        self.label_2.setObjectName("label_2")
        self.fontComboBox = QtWidgets.QFontComboBox(self.page2)
        self.fontComboBox.setGeometry(QtCore.QRect(50, 130, 226, 22))
        self.fontComboBox.setObjectName("fontComboBox")
        self.stackedWidget.addWidget(self.page2)
        self.page3 = QtWidgets.QWidget()
        self.page3.setObjectName("page3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.page3)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.tableWidget = QtWidgets.QTableWidget(self.page3)
        self.tableWidget.setMinimumSize(QtCore.QSize(720, 380))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.stackedWidget.addWidget(self.page3)
        self.page4 = QtWidgets.QWidget()
        self.page4.setObjectName("page4")
        self.pushButton_3 = QtWidgets.QPushButton(self.page4)
        self.pushButton_3.setGeometry(QtCore.QRect(532, 380, 161, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.stackedWidget.addWidget(self.page4)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.label_2.setBuddy(self.fontComboBox)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.pushButton_3.clicked.connect(MainWindow.close) # type: ignore
        self.fontComboBox.currentTextChanged['QString'].connect(self.label_2.setText) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Probando QDialog"))
        self.btn1.setText(_translate("MainWindow", "inicio"))
        self.btn2.setText(_translate("MainWindow", "pagina2"))
        self.btn3.setText(_translate("MainWindow", "pagina3"))
        self.btn4.setText(_translate("MainWindow", "pagina4"))
        self.label.setText(_translate("MainWindow", "Nombre:"))
        self.pushButton.setText(_translate("MainWindow", "Ingresar"))
        self.label_2.setText(_translate("MainWindow", "dibuja algo"))
        self.label_3.setText(_translate("MainWindow", "pagina 3"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "dni"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "nombre"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "localidad"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "provincia"))
        self.pushButton_3.setText(_translate("MainWindow", "salir"))
